apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaargohelm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: javaargohelm
  template:
    metadata:
      labels:
        app: javaargohelm
    spec:
      containers:
      - image: nginx
        name: javaargohelm
        ports:
        - containerPort: 80